permalink: /:year:month:day/:title
url: https://codigo8a.github.io
baseurl: /raiz

# variables
name: h01000110
description: things
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
